version: '3'
services:
  db:
    ports:
      - 3306:3306
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: kate_style
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 80:80
    environment:
      - PMA_HOST=db
